name: Update file links in README

on:
 push:
    branches:
      - main

jobs:
 update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - name: Get last commit author's username
        id: get_author
        run: |
              # Fetch the last commit information
              LAST_COMMIT_INFO=$(git log -1 --pretty=format:"%an <%ae>")
              echo "LAST_COMMIT_INFO=$LAST_COMMIT_INFO" >> $GITHUB_ENV

      - name: Check if commit author is GitHub Actions
        run: |
              if [ "${{ env.LAST_COMMIT_INFO }}" == "github-actions[bot] <github-actions[bot]@users.noreply.github.com>" ]; then
              echo "Commit made by GitHub Actions bot. Skipping workflow."
              exit 78  # Skip the workflow
              else
              echo "Commit made by user. Continue with the workflow."
              fi

      - name: Get the latest commit ID
        id: get_commit_id
        run: echo "::set-output name=commit_id::$(git rev-parse --short HEAD)"

      - name: Replace placeholder in README.md
        run: |
        
          sed -i "s/@[^/]*\//@${{ steps.get_commit_id.outputs.commit_id }}\//g" README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "chore: update CDN links with latest commit hash"
          git push
